on:
  workflow_dispatch: 
  push:

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - run: |
          echo "HTTPS Proxy: $https_proxy"
          echo "HTTP Proxy: $http_proxy"
          echo "No Proxy: $no_proxy"
          curl -v -x http://proxyuser:password@localhost:3128 httpbin.org/ip
          curl -v -x http://proxyuser:password123@localhost:3128 httpbin.org/ip
          curl -v https://httpbin.org/ip