on:
  workflow_dispatch: 
  push:

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - run: |
          echo "HTTPS Proxy: $https_proxy"
          echo "HTTP Proxy: $http_proxy"
          echo "No Proxy: $no_proxy"
          curl -v https://httpbin.org/ip