on:
  workflow_dispatch: 
  push:

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - run: |
          curl -svk https://httpbin.org/ip

      - run: |
          curl -svk -x http://proxyuser:password123@localhost:3128 httpbin.org/ip

      - name: ok
        continue-on-error: true
        run: |
          echo "HTTPS Proxy: $https_proxy"
          echo "HTTP Proxy: $http_proxy"
          echo "No Proxy: $no_proxy"
          curl -sv httpbin.org/ip